var N = null;var sourcesIndex = {};
sourcesIndex["access_logger"] = {"name":"","files":["config.rs","lib.rs","logger.rs","stats.rs"]};
sourcesIndex["access_logger_module"] = {"name":"","files":["lib.rs"]};
sourcesIndex["envoy_sdk"] = {"name":"","dirs":[{"name":"abi","dirs":[{"name":"proxy_wasm","files":["hostcalls.rs","mod.rs","types.rs"]}],"files":["mod.rs"]},{"name":"extension","dirs":[{"name":"access_logger","files":["context.rs","mod.rs","ops.rs"]},{"name":"factory","files":["context.rs","mod.rs","ops.rs"]},{"name":"filter","dirs":[{"name":"http","files":["context.rs","mod.rs","ops.rs"]},{"name":"network","files":["context.rs","mod.rs","ops.rs"]}],"files":["mod.rs"]},{"name":"module","files":["config.rs","dispatcher.rs","mod.rs","start.rs"]}],"files":["error.rs","mod.rs"]},{"name":"host","dirs":[{"name":"http","files":["client.rs"]},{"name":"stream_info","files":["mod.rs","property.rs","proxy_wasm.rs","types.rs"]}],"files":["error.rs","http.rs","log.rs","mod.rs","shared_data.rs","shared_queue.rs","stats.rs","time.rs","types.rs"]}],"files":["error.rs","lib.rs"]};
sourcesIndex["envoy_sdk_test"] = {"name":"","dirs":[{"name":"host","files":["mod.rs","time.rs"]}],"files":["lib.rs"]};
sourcesIndex["http_filter"] = {"name":"","files":["config.rs","factory.rs","filter.rs","lib.rs","stats.rs"]};
sourcesIndex["http_filter_module"] = {"name":"","files":["lib.rs"]};
sourcesIndex["network_filter"] = {"name":"","files":["config.rs","factory.rs","filter.rs","lib.rs","stats.rs"]};
sourcesIndex["network_filter_module"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
